# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Swift 6.0.0
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: '6.0.0'  # Specify the required Swift version

      - name: Verify Swift version
        run: swift --version

      - name: Build project
        run: swift build

      - name: Run tests
        run: swift test
